### PR TITLE
Added fred icon to header to fast toggle on and off the fred console.

### PR DESCRIPTION
**Pull request by rolfschmidt**
Hi OTRS,
I developed a small new feature for the Fred module to fast turn off and on the fred console permanently.

I would appreciate a merge of this feature if you like it.

# OFF

fred_feature_off

# ON

fred_feature_on

Best regards,
Rolf

### CODE REVIEW

**Comment by thorsteneckel** [comment]
danke roter pfeil

:+1:

**Comment by mgruner** [comment]
Hello @rolfschmidt. Screenshots look promising! Could you sign the CLA please?

**Comment by mgruner** [comment]
Hello @rolfschmidt, do you see a problem with the CLA?

**Comment by rolfschmidt** [comment]
Hi Martin,
no problem but i have no printer here. I hope i will have time to sign it and to send it to you at the weekend. So we need to postpone this for a while i think. Sorry

**Comment by mgruner** [comment]
Thanks for the update!

Am 08.09.15 um 11:42 schrieb Rolf Schmidt:
> Hi Martin,
> no problem but i have no printer here. I hope i will have time to sign
> it and to send it to you at the weekend. So we need to postpone this for
> a while i think. Sorry
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OTRS/Fred/pull/2#issuecomment-138497164>.
> 

-- 
Martin Gruner
Team Lead R&D

OTRS AG
Bahnhofplatz 1a
94315 Straubing

T: +49 (0)6172 681988 0
F: +49 (0)9421 56818 18
I:  www.otrs.com/

Geschäftssitz: Bad Homburg, Amtsgericht: Bad Homburg, HRB 10751,
USt-Nr.: DE256610065
Aufsichtsratsvorsitzender: Burchard Steinbild, Vorstand: André
Mindermann (Vorsitzender), Christopher Kuhn, Sabine Riedel

Mobile Kommunikation und transparente Prozesse mit der OTRS Business
Solution™ 5 - Preview auf der IT&Business vom 29.09.-01.10.2015 in Stuttgart
Registrieren Sie sich hier für eine Freikarte:
https://www.otrs.com/meet-otrs-it-business-am-29-09-01-10-in-stuttgart/?lang=de&utm_id=140

**Comment by mgruner** [comment]
Hello Rolf,
any news on this one?
Best regards, Martin

Am 08.09.15 um 11:42 schrieb Rolf Schmidt:
> Hi Martin,
> no problem but i have no printer here. I hope i will have time to sign
> it and to send it to you at the weekend. So we need to postpone this for
> a while i think. Sorry
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OTRS/Fred/pull/2#issuecomment-138497164>.
> 

-- 
Martin Gruner
Team Lead R&D

OTRS AG
Bahnhofplatz 1a
94315 Straubing

T: +49 (0)6172 681988 0
F: +49 (0)9421 56818 18
I:  www.otrs.com/

Geschäftssitz: Bad Homburg, Amtsgericht: Bad Homburg, HRB 10751,
USt-Nr.: DE256610065
Aufsichtsratsvorsitzender: Burchard Steinbild, Vorstand: André
Mindermann (Vorsitzender), Christopher Kuhn, Sabine Riedel

Mobile Kommunikation und transparente Prozesse - Mit der OTRS Business
Solution™ Managed 5 schnell und ohne eigene IT-Ressourcen starten  -
Jetzt neue Features entdecken und bestellen
https://www.otrs.com/neu-in-otrs-business-solution-5-mobile-kommunikation-transparente-prozesse/?lang=de

**Comment by mgruner** [comment]
Hello @rolfschmidt,
sorry, but without a CLA I have to close this unmerged. Please either sign our CLA or route this through Thorsten, if you must object. Then all commits have to originate from him.
Regards, Martin

**Pull request closed without merging**
