### PR TITLE
Switch to https

### PR DESCRIPTION
**Pull request by urbalazs**
Hi @mgruner 
See: https://github.com/OTRS/otrs/pull/1678

### CODE REVIEW

**Comment by urbalazs** [comment]
Hi @mrcbnsls 
Can you check this PR? Minor change only.

**Comment by urbalazs** [comment]
Hi @mrcbnsls 
Can you check this PR? Minor change only.

**Comment by mgruner** [comment]
Since @mrcbnsls refuses to look at this ;), I finally merged it in 5862f84d1c9293fb04a934ce15a983cd594e533a. Thanks @urbalazs!

**Comment by mrcbnsls** [comment]
I'm so sorry @urbalazs and @mgruner. :-( Thanks for merging this!

**Pull request closed without merging**
